# Use an official Node.js image as the base image
FROM node:22.13.0

# Set the working directory in the container
WORKDIR /app

# Copy the app code to the working directory
COPY verifier/ ./

# Copy package.json and package-lock.json to the working directory
#COPY verifier/package.json ./

# Install dependencies
#RUN  npm config set registry https://registry.npmjs.com/
RUN npm install
#RUN npm install && npm cache clean --force && npm install -g typescript

# Expose the port on which the Node.js app will run
EXPOSE 3000

# Command to start the Node.js app
#CMD ["sh", "-c", "npm install && npm start"]
#CMD ["bash", "-c", "env && pwd && ls -la /app/node_modules/ && which -a tsc && npm start"]
CMD ["npm", "start"]
#ENTRYPOINT ["bash"]
