# Use an official Node.js image as the base image
FROM node:22.13.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the app code to the working directory
COPY . ./

# Expose the port on which the Node.js app will run
EXPOSE 8888

# Command to start the Node.js application
CMD ["npm", "start"]
#ENTRYPOINT ["bash"]
