# Use an official Node.js image as the base image
FROM node:23.7.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and lockfile to the working directory
ARG CRYPTO_PLATFORM
COPY frontend-${CRYPTO_PLATFORM}/package.json ./
COPY frontend-${CRYPTO_PLATFORM}/yarn.lock ./

# Install dependencies
RUN yarn install
#RUN yarn install --frozen-lockfile

# Copy the app code to the working directory
COPY frontend-${CRYPTO_PLATFORM}/ ./

# Copy the environment file
ARG TARGET_ENV
COPY docker/env-subkey-ui-${TARGET_ENV} ./.env

# Expose the port on which the app will run
EXPOSE 5173

# Command to start the js app
CMD ["yarn", "dev"]
