# Use an official Node.js image as the base image
#FROM node:22.13.0
FROM node:23.7.0

# Set the working directory in the container
WORKDIR /app

# Copy the app code to the working directory
COPY frontend/ ./

# Copy package.json and package-lock.json to the working directory
#COPY frontend/package*.json ./

# Install dependencies
RUN yarn --pure-lockfile

# Copy the environment file
ARG TARGET_ENV
COPY docker/env-subkey-ui-${TARGET_ENV} ./.env

# Expose the port on which the app will run
EXPOSE 5173

# Command to start the js app
CMD ["yarn", "dev"]
#ENTRYPOINT ["bash"]
