# Use an official Node.js image as the base image
FROM node:22.13.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and lockfile to the working directory
COPY verifier/package.json ./
COPY verifier/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the app code to the working directory
COPY verifier/ ./

# Copy the environment file
ARG TARGET_ENV
COPY docker/env-subkey-verifier-${TARGET_ENV} ./.env

# Expose the port on which the Node.js app will run
EXPOSE 3000

# Command to start the Node.js app
CMD ["npm", "start"]
