FROM mongo:7.0.2

ARG CRYPTO_PLATFORM
ENV CRYPTO_PLATFORM=${CRYPTO_PLATFORM}

ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=root
ENV MONGO_INITDB_DATABASE=subkeydb

COPY docker/subkeydb.publickey.${CRYPTO_PLATFORM}.json /tmp/subkeydb.publickey.${CRYPTO_PLATFORM}.json
COPY docker/mongo-import.sh /docker-entrypoint-initdb.d/

EXPOSE 27017

ADD docker/mongo-init.js /docker-entrypoint-initdb.d/
